name: FlectoneChatReborn
version: '${version}'
main: net.flectone.chat.reborn.FlectoneChatReborn
api-version: '1.16'
authors: [ TheFaser, fxd, GideonWhite1029 ]
loadbefore: [ Essentials ]
softdepend: [ DiscordSRV, PlaceholderAPI, InteractiveChat, LuckPerms, SuperVanish, Vault, PlasmoVoice, voicechat, SkinsRestorer ]

permissions:

  flectonechatreborn.auto-message:
    default: true
  flectonechatreborn.chat-bubble:
    default: true
  flectonechatreborn.extra.item-sign:
    default: true
  flectonechatreborn.extra.item-sign.unsign:
    default: true
  flectonechatreborn.extra.knocking:
    default: true
  flectonechatreborn.extra.knocking.door:
    default: true
  flectonechatreborn.extra.knocking.glass:
    default: true
  flectonechatreborn.extra.mark:
    default: true
  flectonechatreborn.extra.spit:
    default: true
  flectonechatreborn.player.afk-timeout:
    default: true
  flectonechatreborn.player.hover:
    default: true
  flectonechatreborn.player.name.invisible:
    default: true
  flectonechatreborn.player.name.prefix:
    default: true
  flectonechatreborn.player.name.suffix:
    default: true
  flectonechatreborn.player.name.real:
    default: true
  flectonechatreborn.player.name.display:
    default: true
  flectonechatreborn.player.name.tab:
    default: true
  flectonechatreborn.player.name-tag.sort:
    default: true
  flectonechatreborn.player.name-tag.visible:
    default: true
  flectonechatreborn.player.right-click:
    default: true
  flectonechatreborn.player.world:
    default: true
  flectonechatreborn.player-message.anvil:
    default: true
  flectonechatreborn.player-message.book:
    default: true
  flectonechatreborn.player-message.chat:
    default: true
  flectonechatreborn.player-message.chat.local:
    default: true
  flectonechatreborn.player-message.chat.global:
    default: true
  flectonechatreborn.player-message.colors:
    default: op
  flectonechatreborn.player-message.placeholders:
    default: op
  flectonechatreborn.player-message.formatting:
    default: true
  flectonechatreborn.player-message.formatting.ping:
    default: true
  flectonechatreborn.player-message.formatting.cords:
    default: true
  flectonechatreborn.player-message.formatting.stats:
    default: true
  flectonechatreborn.player-message.formatting.skin:
    default: true
  flectonechatreborn.player-message.formatting.url:
    default: true
  flectonechatreborn.player-message.formatting.markdown-url:
    default: true
  flectonechatreborn.player-message.formatting.url.image:
    default: true
  flectonechatreborn.player-message.formatting.item:
    default: true
  flectonechatreborn.player-message.formatting.mention:
    default: true
  flectonechatreborn.player-message.formatting.markdown-||:
    default: true
  flectonechatreborn.player-message.formatting.markdown-**:
    default: true
  flectonechatreborn.player-message.formatting.markdown-##:
    default: true
  flectonechatreborn.player-message.formatting.markdown-__:
    default: true
  flectonechatreborn.player-message.formatting.markdown-??:
    default: true
  flectonechatreborn.player-message.formatting.markdown-~~:
    default: true
  flectonechatreborn.player-message.patterns:
    default: true
  flectonechatreborn.player-message.sign:
    default: true
  flectonechatreborn.player-message.swear-protection:
    default: true
  flectonechatreborn.player-message.swear-protection.bypass:
    default: op
  flectonechatreborn.server.brand:
    default: true
  flectonechatreborn.server.tab.header:
    default: true
  flectonechatreborn.server.tab.footer:
    default: true
  flectonechatreborn.server.tab.player-list-name:
    default: true
  flectonechatreborn.server-message.advancement:
    default: true
  flectonechatreborn.server-message.death:
    default: true
  flectonechatreborn.server-message.join:
    default: true
  flectonechatreborn.server-message.greeting:
    default: true
  flectonechatreborn.server-message.quit:
    default: true
  flectonechatreborn.sounds:
    default: true
  flectonechatreborn.sounds.mention:
    default: true
  flectonechatreborn.sounds.auto-message:
    default: true
  flectonechatreborn.sounds.player.afk-timeout-true:
    default: true
  flectonechatreborn.sounds.player.afk-timeout-false:
    default: true
  flectonechatreborn.sounds.player.right-click:
    default: true
  flectonechatreborn.sounds.player-message.anvil:
    default: true
  flectonechatreborn.sounds.player-message.book:
    default: true
  flectonechatreborn.sounds.player-message.sign:
    default: true
  flectonechatreborn.sounds.player-message.chat.local:
    default: true
  flectonechatreborn.sounds.player-message.chat.global:
    default: true
  flectonechatreborn.sounds.extra.item-sign:
    default: true
  flectonechatreborn.sounds.extra.item-sign.unsign:
    default: true
  flectonechatreborn.sounds.extra.knocking.door:
    default: true
  flectonechatreborn.sounds.extra.knocking.glass:
    default: true
  flectonechatreborn.sounds.extra.mark:
    default: true
  flectonechatreborn.sounds.extra.spit:
    default: true
  flectonechatreborn.sounds.server-message.advancement:
    default: true
  flectonechatreborn.sounds.server-message.death:
    default: true
  flectonechatreborn.sounds.server-message.join:
    default: true
  flectonechatreborn.sounds.server-message.greeting:
    default: true
  flectonechatreborn.sounds.server-message.quit:
    default: true
  flectonechatreborn.sounds.commands.spit:
    default: true
  flectonechatreborn.sounds.commands.kick:
    default: true
  flectonechatreborn.sounds.commands.warn:
    default: true
  flectonechatreborn.sounds.commands.unwarn:
    default: true
  flectonechatreborn.sounds.commands.warnlist:
    default: true
  flectonechatreborn.sounds.commands.spy:
    default: true
  flectonechatreborn.sounds.commands.poll:
    default: true
  flectonechatreborn.sounds.commands.broadcast:
    default: true
  flectonechatreborn.sounds.commands.unban:
    default: true
  flectonechatreborn.sounds.commands.tempban:
    default: true
  flectonechatreborn.sounds.commands.clearchat:
    default: true
  flectonechatreborn.sounds.commands.chatsettings:
    default: true
  flectonechatreborn.sounds.commands.chatcolor:
    default: true
  flectonechatreborn.sounds.commands.flectonechat:
    default: true
  flectonechatreborn.sounds.commands.geolocate:
    default: true
  flectonechatreborn.sounds.commands.ignore:
    default: true
  flectonechatreborn.sounds.commands.ignorelist:
    default: true
  flectonechatreborn.sounds.commands.mail:
    default: true
  flectonechatreborn.sounds.commands.helper:
    default: true
  flectonechatreborn.sounds.commands.mark:
    default: true
  flectonechatreborn.sounds.commands.me:
    default: true
  flectonechatreborn.sounds.commands.tell:
    default: true
  flectonechatreborn.sounds.commands.ping:
    default: true
  flectonechatreborn.sounds.commands.reply:
    default: true
  flectonechatreborn.sounds.commands.clearmail:
    default: true
  flectonechatreborn.sounds.commands.stream:
    default: true
  flectonechatreborn.sounds.commands.translateto:
    default: true
  flectonechatreborn.sounds.commands.try:
    default: true
  flectonechatreborn.sounds.commands.dice:
    default: true
  flectonechatreborn.sounds.commands.afk:
    default: true
  flectonechatreborn.sounds.commands.mute:
    default: true
  flectonechatreborn.sounds.commands.unmute:
    default: true
  flectonechatreborn.sounds.commands.maintenance:
    default: true
  flectonechatreborn.sounds.commands.ball:
    default: true
  flectonechatreborn.sounds.commands.tictactoe:
    default: true
  flectonechatreborn.sounds.commands.banlist:
    default: true
  flectonechatreborn.sounds.commands.mutelist:
    default: true
  flectonechatreborn.server.status.player-count.bypass:
    default: op
  flectonechatreborn.commands.afk:
    default: true
  flectonechatreborn.commands.ball:
    default: true
  flectonechatreborn.commands.ban:
    default: op
  flectonechatreborn.commands.ban.bypass:
    default: false
  flectonechatreborn.commands.banlist:
    default: op
  flectonechatreborn.commands.me:
    default: true
  flectonechatreborn.commands.broadcast:
    default: op
  flectonechatreborn.commands.chatcolor.other:
    default: op
  flectonechatreborn.commands.chatcolor:
    default: true
  flectonechatreborn.commands.chatsettings:
    default: true
  flectonechatreborn.commands.chatsettings.advancement:
    default: true
  flectonechatreborn.commands.chatsettings.death:
    default: true
  flectonechatreborn.commands.chatsettings.join:
    default: true
  flectonechatreborn.commands.chatsettings.greeting:
    default: true
  flectonechatreborn.commands.chatsettings.quit:
    default: true
  flectonechatreborn.commands.chatsettings.auto-message:
    default: true
  flectonechatreborn.commands.chatsettings.me:
    default: true
  flectonechatreborn.commands.chatsettings.try:
    default: true
  flectonechatreborn.commands.chatsettings.dice:
    default: true
  flectonechatreborn.commands.chatsettings.ball:
    default: true
  flectonechatreborn.commands.chatsettings.ban:
    default: true
  flectonechatreborn.commands.chatsettings.mute:
    default: true
  flectonechatreborn.commands.chatsettings.warn:
    default: true
  flectonechatreborn.commands.chatsettings.tell:
    default: true
  flectonechatreborn.commands.chatsettings.reply:
    default: true
  flectonechatreborn.commands.chatsettings.mail:
    default: true
  flectonechatreborn.commands.chatsettings.tictactoe:
    default: true
  flectonechatreborn.commands.chatsettings.kick:
    default: true
  flectonechatreborn.commands.chatsettings.local:
    default: true
  flectonechatreborn.commands.chatsettings.global:
    default: true
  flectonechatreborn.commands.chatsettings.default:
    default: true
  flectonechatreborn.commands.clearchat:
    default: true
  flectonechatreborn.commands.clearchat.other:
    default: op
  flectonechatreborn.commands.firstonline:
    default: true
  flectonechatreborn.commands.flectonechat:
    default: op
  flectonechatreborn.commands.helper:
    default: true
  flectonechatreborn.commands.helper.other:
    default: op
  flectonechatreborn.commands.ignore:
    default: true
  flectonechatreborn.commands.ignorelist:
    default: true
  flectonechatreborn.commands.kick:
    default: op
  flectonechatreborn.commands.kick.bypass:
    default: false
  flectonechatreborn.commands.lastonline:
    default: true
  flectonechatreborn.commands.mail:
    default: true
  flectonechatreborn.commands.clearmail:
    default: true
  flectonechatreborn.commands.maintenance:
    default: op
  flectonechatreborn.commands.mark:
    default: true
  flectonechatreborn.commands.tell:
    default: true
  flectonechatreborn.commands.mute:
    default: op
  flectonechatreborn.commands.mute.bypass:
    default: false
  flectonechatreborn.commands.mutelist:
    default: op
  flectonechatreborn.commands.ping:
    default: true
  flectonechatreborn.commands.poll:
    default: true
  flectonechatreborn.commands.poll.create:
    default: op
  flectonechatreborn.commands.reply:
    default: true
  flectonechatreborn.commands.spit:
    default: true
  flectonechatreborn.commands.spy:
    default: op
  flectonechatreborn.commands.stream:
    default: false
  flectonechatreborn.commands.tictactoe:
    default: true
  flectonechatreborn.commands.translateto:
    default: true
  flectonechatreborn.commands.try:
    default: true
  flectonechatreborn.commands.dice:
    default: true
  flectonechatreborn.commands.unban:
    default: op
  flectonechatreborn.commands.unmute:
    default: op
  flectonechatreborn.commands.warn:
    default: op
  flectonechatreborn.commands.warn.bypass:
    default: false
  flectonechatreborn.commands.unwarn:
    default: op
  flectonechatreborn.commands.warnlist:
    default: op
  flectonechatreborn.commands.geolocate:
    default: op