name: Build Gradle project

on:
  push:
    branches:
      - master

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 16

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: ./gradlew shadowJar

      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: FlectoneChatReborn
          path: build/libs